/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HomeRouteImport } from './routes/_home'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as HomeIndexRouteImport } from './routes/_home/index'
import { Route as HomeStudentsRouteImport } from './routes/_home/students'
import { Route as HomeCoursesRouteImport } from './routes/_home/courses'
import { Route as HomeAboutRouteImport } from './routes/_home/about'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'

const HomeRoute = HomeRouteImport.update({
  id: '/_home',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeRoute,
} as any)
const HomeStudentsRoute = HomeStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => HomeRoute,
} as any)
const HomeCoursesRoute = HomeCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => HomeRoute,
} as any)
const HomeAboutRoute = HomeAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => HomeRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof AuthLoginRoute
  '/about': typeof HomeAboutRoute
  '/courses': typeof HomeCoursesRoute
  '/students': typeof HomeStudentsRoute
  '/': typeof HomeIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof AuthLoginRoute
  '/about': typeof HomeAboutRoute
  '/courses': typeof HomeCoursesRoute
  '/students': typeof HomeStudentsRoute
  '/': typeof HomeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_home': typeof HomeRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_home/about': typeof HomeAboutRoute
  '/_home/courses': typeof HomeCoursesRoute
  '/_home/students': typeof HomeStudentsRoute
  '/_home/': typeof HomeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login' | '/about' | '/courses' | '/students' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/about' | '/courses' | '/students' | '/'
  id:
    | '__root__'
    | '/_auth'
    | '/_home'
    | '/_auth/login'
    | '/_home/about'
    | '/_home/courses'
    | '/_home/students'
    | '/_home/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  HomeRoute: typeof HomeRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_home': {
      id: '/_home'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_home/': {
      id: '/_home/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof HomeRoute
    }
    '/_home/students': {
      id: '/_home/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof HomeStudentsRouteImport
      parentRoute: typeof HomeRoute
    }
    '/_home/courses': {
      id: '/_home/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof HomeCoursesRouteImport
      parentRoute: typeof HomeRoute
    }
    '/_home/about': {
      id: '/_home/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof HomeAboutRouteImport
      parentRoute: typeof HomeRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface HomeRouteChildren {
  HomeAboutRoute: typeof HomeAboutRoute
  HomeCoursesRoute: typeof HomeCoursesRoute
  HomeStudentsRoute: typeof HomeStudentsRoute
  HomeIndexRoute: typeof HomeIndexRoute
}

const HomeRouteChildren: HomeRouteChildren = {
  HomeAboutRoute: HomeAboutRoute,
  HomeCoursesRoute: HomeCoursesRoute,
  HomeStudentsRoute: HomeStudentsRoute,
  HomeIndexRoute: HomeIndexRoute,
}

const HomeRouteWithChildren = HomeRoute._addFileChildren(HomeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  HomeRoute: HomeRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
